package com.neu.entity;

import java.math.BigDecimal;

public class EleCust {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ele_cust.card_id
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	private String cardId;
	@Override
	public String toString() {
		return "EleCust [cardId=" + cardId + ", uname=" + uname + ", addr=" + addr + ", ownMoney=" + ownMoney + "]";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ele_cust.uname
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	private String uname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ele_cust.addr
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ele_cust.own_money
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	private BigDecimal ownMoney;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ele_cust.card_id
	 * @return  the value of ele_cust.card_id
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public String getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ele_cust.card_id
	 * @param cardId  the value for ele_cust.card_id
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ele_cust.uname
	 * @return  the value of ele_cust.uname
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ele_cust.uname
	 * @param uname  the value for ele_cust.uname
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ele_cust.addr
	 * @return  the value of ele_cust.addr
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ele_cust.addr
	 * @param addr  the value for ele_cust.addr
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ele_cust.own_money
	 * @return  the value of ele_cust.own_money
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public BigDecimal getOwnMoney() {
		return ownMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ele_cust.own_money
	 * @param ownMoney  the value for ele_cust.own_money
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	public void setOwnMoney(BigDecimal ownMoney) {
		this.ownMoney = ownMoney;
	}
}