package com.neu.entity;

import java.util.Date;

public class MoveBooking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move_booking.id
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move_booking.area
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move_booking.cartype
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    private String cartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move_booking.movedate
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    private Date movedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move_booking.contact
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move_booking.phone
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move_booking.status
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move_booking.id
     *
     * @return the value of move_booking.id
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move_booking.id
     *
     * @param id the value for move_booking.id
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move_booking.area
     *
     * @return the value of move_booking.area
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move_booking.area
     *
     * @param area the value for move_booking.area
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move_booking.cartype
     *
     * @return the value of move_booking.cartype
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move_booking.cartype
     *
     * @param cartype the value for move_booking.cartype
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public void setCartype(String cartype) {
        this.cartype = cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move_booking.movedate
     *
     * @return the value of move_booking.movedate
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public Date getMovedate() {
        return movedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move_booking.movedate
     *
     * @param movedate the value for move_booking.movedate
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public void setMovedate(Date movedate) {
        this.movedate = movedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move_booking.contact
     *
     * @return the value of move_booking.contact
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move_booking.contact
     *
     * @param contact the value for move_booking.contact
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move_booking.phone
     *
     * @return the value of move_booking.phone
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move_booking.phone
     *
     * @param phone the value for move_booking.phone
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move_booking.status
     *
     * @return the value of move_booking.status
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move_booking.status
     *
     * @param status the value for move_booking.status
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}