package com.neu.mapper;

import com.neu.entity.BankCust;
import java.util.List;
import com.neu.entity.BankCustExample;
import org.apache.ibatis.annotations.Param;

public interface BankCustMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	long countByExample(BankCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int deleteByExample(BankCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int deleteByPrimaryKey(String cardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int insert(BankCust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int insertSelective(BankCust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	List<BankCust> selectByExample(BankCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	BankCust selectByPrimaryKey(String cardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByExampleSelective(@Param("record") BankCust record, @Param("example") BankCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByExample(@Param("record") BankCust record, @Param("example") BankCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByPrimaryKeySelective(BankCust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByPrimaryKey(BankCust record);
}