package com.neu.mapper;

import com.neu.entity.EleCust;
import java.util.List;
import com.neu.entity.EleCustExample;
import org.apache.ibatis.annotations.Param;

public interface EleCustMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	long countByExample(EleCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int deleteByExample(EleCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int deleteByPrimaryKey(String cardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int insert(EleCust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int insertSelective(EleCust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	List<EleCust> selectByExample(EleCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	EleCust selectByPrimaryKey(String cardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByExampleSelective(@Param("record") EleCust record, @Param("example") EleCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByExample(@Param("record") EleCust record, @Param("example") EleCustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByPrimaryKeySelective(EleCust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ele_cust
	 * @mbg.generated  Thu Nov 15 09:14:51 CST 2018
	 */
	int updateByPrimaryKey(EleCust record);
}