package com.neu.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neu.entity.MoveBooking;
import com.neu.entity.MoveBookingExample;

public interface MoveBookingMapper {
	List<MoveBooking> getallmovebooking();
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    long countByExample(MoveBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int deleteByExample(MoveBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int insert(MoveBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int insertSelective(MoveBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    List<MoveBooking> selectByExample(MoveBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    MoveBooking selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") MoveBooking record, @Param("example") MoveBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int updateByExample(@Param("record") MoveBooking record, @Param("example") MoveBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int updateByPrimaryKeySelective(MoveBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move_booking
     *
     * @mbg.generated Thu Nov 15 15:36:02 CST 2018
     */
    int updateByPrimaryKey(MoveBooking record);
}